---

- name: Install flatpaks
  hosts: 127.0.0.1
  connection: local
  tasks:

    - name: Install flatpak
      become: true
      ansible.builtin.package:
        name: "flatpak"
        state: latest

    - name: Add the flathub flatpak repository remote
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user

    - name: Install packages
      loop: "{{ lookup('file', 'flatpaks.txt').splitlines() }}"
      community.general.flatpak:
        name: "{{ item }}"
        state: present
        method: user


